homepage = ""
license = "MIT"
name = "Dienstag"
min_version = "0.58.3"
licenselink = "LICENSE"
[author]
  name = "Nenad Filipovic"
  homepage = "https://github.com/nenadfilipovic"
description = "Clean and minimal personal blog and portfolio theme"
tags = ["minimal", "clean", "blog", "responsive", "personal", "simple", "minimalist", "portfolio"]
features = ["blog", "Clean and minimal", "Responsive", "Social media links", "Syntax highlighting"]
